// Generated by CoffeeScript 1.12.6
(function() {
  var spreadsheetId;

  spreadsheetId = "1L-ihOdiGEOVhsmb5pDdqaO-_QfokzEnM6UGBF_Z4WPo";

  POST("https://sheets.googleapis.com/v4/spreadsheets/" + spreadsheetId + "/values/AllResponses!A1:E1:append?valueInputOption=USER_ENTERED");

}).call(this);

//# sourceMappingURL=why-give.js.map
